# Render Deployment Configuration
services:
  - type: web
    name: predicare-voicebot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
